### ISSUE TITLE
Updating/work-with this template for GHA and Azd Devcontainer feature

### ISSUE THREAD

**Issue by v-jiaodi** [lechnerc77/azd-compatibility-azure-function#2]
We are updating this template to support new features in `Github Action` and `Azd Devcontainer`.

**1. For the Github Action feature:** We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
![image](https://github.com/jsburckhardt/docusaurus-aca/assets/80496810/11ce8d77-333a-433b-8437-29325f1e72fb)

**2. For the Azd Devcontainer feature:** We will add the following code in `devcontainer.json` file.
```
"ghcr.io/azure/azure-dev/azd:latest": {}
```
And remove the relevant code for installing azd in `Dockerfile` under `.devcontainer` folder.
```
RUN curl -fsSL https://aka.ms/install-azd.sh | bash 
```
@rajeshkamal5050 , @lechnerc77   for notification.

**Comment by lechnerc77** [comment]
@v-jiaodi Thanks for the heads-up. I will update this repo with the new feature around GH Actions and the devcontainer setup soon.

**Comment by lechnerc77** [comment]
Fixed
